name = "latin-host-inc"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Variables de entorno eliminadas para simplificar el flujo
