name = "latin-host-inc"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_Ofa2Yzxu7VQI@ep-ancient-shape-aqs5yzyx-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
NEON_AUTH_BASE_URL = "https://ep-ancient-shape-aqs5yzyx.neonauth.c-8.us-east-1.aws.neon.tech/neondb/auth"
NEON_AUTH_COOKIE_SECRET = "grIrD1fhwQ1Rq+XE8w8aogO/z7EmZuvO3wjB8lGrAdo="
BETTER_AUTH_SECRET = "grIrD1fhwQ1Rq+XE8w8aogO/z7EmZuvO3wjB8lGrAdo="
BETTER_AUTH_TRUST_HOST = "true"
